services:

  postgres:
    image: postgres:16
    container_name: postgres_db

    expose:
    - "5432"

    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: burratapostgres
      POSTGRES_DB: appdb

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: always



  backend:
    build:
      ./BackEnd

    container_name: BackEnd

    env_file:
       - BackEnd/.env

    depends_on:
      - postgres

    ports:
      - "8000:8000"

    restart: always



  frontend:
    build:
      ./FrontEnd

    container_name: FrontEnd

    ports:
      - "3000:80"

    restart: always



volumes:

  postgres_data:
