"""empty message

Revision ID: 19efcc481cfd
Revises: 9f33e94793aa
Create Date: 2026-06-04 13:06:39.050488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19efcc481cfd'
down_revision: Union[str, Sequence[str], None] = '9f33e94793aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'claimsschedule', ['date', 'username'])
    op.create_unique_constraint(None, 'schedule', ['date', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule', type_='unique')
    op.drop_constraint(None, 'claimsschedule', type_='unique')
    # ### end Alembic commands ###
