"""add schedules FK cascade

Revision ID: 2e6578dfb8e6
Revises: fd7deb5a1e41
Create Date: 2026-06-10 01:18:57.716210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6578dfb8e6'
down_revision: Union[str, Sequence[str], None] = 'fd7deb5a1e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
