"""added department

Revision ID: 42dbac70f75a
Revises: 7cf54a83d02d
Create Date: 2026-07-19 16:03:35.655123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42dbac70f75a'
down_revision: Union[str, Sequence[str], None] = '7cf54a83d02d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defaultweekshifts', sa.Column('department', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defaultweekshifts', 'department')
    # ### end Alembic commands ###
