"""Message table added

Revision ID: 4654080ab056
Revises: b6ed8f3a2274
Create Date: 2026-06-21 16:49:29.777187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4654080ab056'
down_revision: Union[str, Sequence[str], None] = 'b6ed8f3a2274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('messages', sa.Column('message', sa.String(), nullable=False))
    op.add_column('messages', sa.Column('read', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'read')
    op.drop_column('messages', 'message')
    op.drop_column('messages', 'created_at')
    # ### end Alembic commands ###
