"""fixed shiftsValues

Revision ID: 607c912a46b7
Revises: c897e9cba384
Create Date: 2026-07-01 13:07:44.287876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607c912a46b7'
down_revision: Union[str, Sequence[str], None] = 'c897e9cba384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shiftsvalues', sa.Column('max_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shiftsvalues', 'max_count')
    # ### end Alembic commands ###
