"""added default week shifts table

Revision ID: 6373c98b311d
Revises: 3222225b9549
Create Date: 2026-07-09 22:51:04.496285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6373c98b311d'
down_revision: Union[str, Sequence[str], None] = '3222225b9549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defaultweekshifts', sa.Column('first_shift', sa.Integer(), nullable=False))
    op.drop_column('defaultweekshifts', 'firts_shift')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defaultweekshifts', sa.Column('firts_shift', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('defaultweekshifts', 'first_shift')
    # ### end Alembic commands ###
