"""shiftsValues table created

Revision ID: 6f51d2c2d0af
Revises: 8bcb680c2f01
Create Date: 2026-06-30 14:46:48.072673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f51d2c2d0af'
down_revision: Union[str, Sequence[str], None] = '8bcb680c2f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shiftsValues', sa.Column('username', sa.String(), nullable=False))
    op.add_column('shiftsValues', sa.Column('day', sa.String(), nullable=False))
    op.add_column('shiftsValues', sa.Column('shiftValue', sa.String(), nullable=False))
    op.add_column('shiftsValues', sa.Column('allowed', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'shiftsValues', ['username'])
    op.create_foreign_key(None, 'shiftsValues', 'users', ['username'], ['username'], ondelete='CASCADE')
    op.alter_column('vacations', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('vacations', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'vacations', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacations', type_='unique')
    op.alter_column('vacations', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('vacations', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'shiftsValues', type_='foreignkey')
    op.drop_constraint(None, 'shiftsValues', type_='unique')
    op.drop_column('shiftsValues', 'allowed')
    op.drop_column('shiftsValues', 'shiftValue')
    op.drop_column('shiftsValues', 'day')
    op.drop_column('shiftsValues', 'username')
    # ### end Alembic commands ###
