"""empty message

Revision ID: 7c6d94175de0
Revises: 19efcc481cfd
Create Date: 2026-06-04 13:28:28.178412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6d94175de0'
down_revision: Union[str, Sequence[str], None] = '19efcc481cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'shift',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'shift',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
