"""fixed shiftsValues

Revision ID: 7c8eb2ce2ec6
Revises: 607c912a46b7
Create Date: 2026-07-01 14:44:54.984966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8eb2ce2ec6'
down_revision: Union[str, Sequence[str], None] = '607c912a46b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maxshiftsweektotal', sa.Column('shiftvalue', sa.String(), nullable=False))
    op.drop_column('maxshiftsweektotal', 'shiftValue')
    op.add_column('shiftsvalues', sa.Column('shiftvalue', sa.String(), nullable=False))
    op.drop_column('shiftsvalues', 'shiftValue')
    op.drop_column('shiftsvalues', 'max_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shiftsvalues', sa.Column('max_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shiftsvalues', sa.Column('shiftValue', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('shiftsvalues', 'shiftvalue')
    op.add_column('maxshiftsweektotal', sa.Column('shiftValue', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('maxshiftsweektotal', 'shiftvalue')
    # ### end Alembic commands ###
