"""add position and is_trainee in users  column

Revision ID: 87d62e4edf20
Revises: 7c6d94175de0
Create Date: 2026-06-07 15:49:35.480149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d62e4edf20'
down_revision: Union[str, Sequence[str], None] = '7c6d94175de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('position', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_trainee', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'users', ['position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_trainee')
    op.drop_column('users', 'position')
    # ### end Alembic commands ###
