"""vacations table added

Revision ID: 8bcb680c2f01
Revises: b4aa51d6becb
Create Date: 2026-06-24 21:58:48.578650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcb680c2f01'
down_revision: Union[str, Sequence[str], None] = 'b4aa51d6becb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacations', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('vacations', sa.Column('end_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacations', 'end_date')
    op.drop_column('vacations', 'start_date')
    # ### end Alembic commands ###
