"""removing Enum from claimsschedule

Revision ID: 9f33e94793aa
Revises: cb1718f13723
Create Date: 2026-05-29 11:07:15.523451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f33e94793aa'
down_revision: Union[str, Sequence[str], None] = 'cb1718f13723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claimsschedule', 'shift',
               existing_type=postgresql.ENUM('FIRST', 'SECOND', 'X', 'LONG_TWELFE', 'LONG_TEN', name='choice'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claimsschedule', 'shift',
               existing_type=sa.String(),
               type_=postgresql.ENUM('FIRST', 'SECOND', 'X', 'LONG_TWELFE', 'LONG_TEN', name='choice'),
               existing_nullable=False)
    # ### end Alembic commands ###
