"""bug fixed

Revision ID: b6ed8f3a2274
Revises: 2e6578dfb8e6
Create Date: 2026-06-10 01:23:23.181573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ed8f3a2274'
down_revision: Union[str, Sequence[str], None] = '2e6578dfb8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('claimsschedule_username_fkey'), 'claimsschedule', type_='foreignkey')
    op.create_foreign_key(None, 'claimsschedule', 'users', ['username'], ['username'], ondelete='CASCADE')
    op.drop_constraint(op.f('schedule_username_fkey'), 'schedule', type_='foreignkey')
    op.create_foreign_key(None, 'schedule', 'users', ['username'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.create_foreign_key(op.f('schedule_username_fkey'), 'schedule', 'users', ['username'], ['username'])
    op.drop_constraint(None, 'claimsschedule', type_='foreignkey')
    op.create_foreign_key(op.f('claimsschedule_username_fkey'), 'claimsschedule', 'users', ['username'], ['username'])
    # ### end Alembic commands ###
