"""add user_unique_id_number  to claimschedule

Revision ID: c299d093f339
Revises: a81bb3e9b7c9
Create Date: 2026-05-20 20:16:55.744286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c299d093f339'
down_revision: Union[str, Sequence[str], None] = 'a81bb3e9b7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claimsschedule', sa.Column('user_unique_id_number', sa.String(), nullable=False))
    op.create_foreign_key(None, 'claimsschedule', 'users', ['user_unique_id_number'], ['unique_id_number'])
    op.create_foreign_key(None, 'claimsschedule', 'users', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claimsschedule', type_='foreignkey')
    op.drop_constraint(None, 'claimsschedule', type_='foreignkey')
    op.drop_column('claimsschedule', 'user_unique_id_number')
    # ### end Alembic commands ###
