"""fixed shiftsValues table name

Revision ID: c3cdc0baa127
Revises: 6f51d2c2d0af
Create Date: 2026-07-01 12:15:22.594653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3cdc0baa127'
down_revision: Union[str, Sequence[str], None] = '6f51d2c2d0af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shiftsValues_id'), table_name='shiftsValues')
    op.drop_table('shiftsValues')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shiftsValues',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('day', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shiftValue', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('allowed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], name=op.f('shiftsValues_username_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('shiftsValues_pkey')),
    sa.UniqueConstraint('username', name=op.f('shiftsValues_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_shiftsValues_id'), 'shiftsValues', ['id'], unique=False)
    # ### end Alembic commands ###
