"""fixed shiftsValues

Revision ID: c897e9cba384
Revises: c3cdc0baa127
Create Date: 2026-07-01 12:35:58.065181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c897e9cba384'
down_revision: Union[str, Sequence[str], None] = 'c3cdc0baa127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('shiftsvalues_username_key'), 'shiftsvalues', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('shiftsvalues_username_key'), 'shiftsvalues', ['username'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
