"""remove user_id_uniqe

Revision ID: cb1718f13723
Revises: c299d093f339
Create Date: 2026-05-20 20:59:21.105361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1718f13723'
down_revision: Union[str, Sequence[str], None] = 'c299d093f339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('claimsschedule_user_unique_id_number_fkey'), 'claimsschedule', type_='foreignkey')
    op.drop_column('claimsschedule', 'user_unique_id_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claimsschedule', sa.Column('user_unique_id_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('claimsschedule_user_unique_id_number_fkey'), 'claimsschedule', 'users', ['user_unique_id_number'], ['unique_id_number'])
    # ### end Alembic commands ###
