"""add user_unique_id_number  to claimschedule

Revision ID: d79804706235
Revises: 
Create Date: 2026-05-20 20:14:12.350621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd79804706235'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claimsschedule', sa.Column('user_unique_id_number', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'claimsschedule', 'users', ['user_unique_id_number'], ['unique_id_number'])
    op.create_foreign_key(None, 'claimsschedule', 'users', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claimsschedule', type_='foreignkey')
    op.drop_constraint(None, 'claimsschedule', type_='foreignkey')
    op.drop_column('claimsschedule', 'user_unique_id_number')
    # ### end Alembic commands ###
