"""added uniqueConstraint"

Revision ID: e9ff1ade421c
Revises: 42dbac70f75a
Create Date: 2026-07-19 16:17:52.981188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ff1ade421c'
down_revision: Union[str, Sequence[str], None] = '42dbac70f75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('defaultweekshifts_day_key'), 'defaultweekshifts', type_='unique')
    op.create_unique_constraint(None, 'defaultweekshifts', ['day', 'department'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'defaultweekshifts', type_='unique')
    op.create_unique_constraint(op.f('defaultweekshifts_day_key'), 'defaultweekshifts', ['day'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
