"""removed unique from position

Revision ID: fd7deb5a1e41
Revises: 87d62e4edf20
Create Date: 2026-06-07 23:11:38.919109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7deb5a1e41'
down_revision: Union[str, Sequence[str], None] = '87d62e4edf20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_position_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_position_key'), 'users', ['position'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
